"""
inference.py — Full inference pipeline: silent EMG → audio.

Section 4: "We run experiments to measure intelligibility of audio
generated by our model from silent EMG signals E_S."

Pipeline:
  1. Load silent EMG signal
  2. Extract & normalize features
  3. Transducer: EMG features → predicted MFCCs
  4. WaveNet: MFCCs → audio waveform
  5. (Optional) ASR evaluation for WER

Usage:
    python inference.py --emg_path test_emg.npy --output_dir outputs/
"""

import os
import sys
import argparse
import numpy as np
import torch
import soundfile as sf

from config import FullConfig
from models.transducer import EMGTransducer
from models.wavenet import WaveNetSynthesizer
from features.emg_features import (
    preprocess_emg, extract_emg_features, FeatureNormalizer
)
from features.audio_features import mu_law_decode


def load_transducer(checkpoint_path: str, device: torch.device):
    """Load trained transducer model."""
    ckpt = torch.load(checkpoint_path, map_location=device)
    cfg = ckpt['config']
    model = EMGTransducer(cfg.transducer, n_sessions=cfg.n_sessions).to(device)
    model.load_state_dict(ckpt['model_state'])
    model.eval()
    return model, cfg


def load_wavenet(checkpoint_path: str, device: torch.device, cfg: FullConfig):
    """Load trained WaveNet model."""
    ckpt = torch.load(checkpoint_path, map_location=device)
    model = WaveNetSynthesizer(cfg.wavenet).to(device)
    model.load_state_dict(ckpt['model_state'])
    model.eval()
    return model


class SilentSpeechPipeline:
    """
    End-to-end inference: raw silent EMG → audio waveform.
    """

    def __init__(self, transducer_ckpt: str, wavenet_ckpt: str,
                 normalizer_path: str, device: str = 'cpu'):
        self.device = torch.device(device)
        self.cfg = FullConfig()

        # Load models
        print("Loading transducer...")
        self.transducer, loaded_cfg = load_transducer(
            transducer_ckpt, self.device
        )
        self.cfg = loaded_cfg

        print("Loading WaveNet...")
        self.wavenet = load_wavenet(wavenet_ckpt, self.device, self.cfg)

        # Load normalizers
        import pickle
        with open(normalizer_path, 'rb') as f:
            norm_data = pickle.load(f)

        self.emg_normalizer = FeatureNormalizer()
        self.emg_normalizer.load_state_dict(norm_data['emg_normalizer'])

        # Audio normalizer (for de-normalizing predictions if needed)
        self.audio_normalizer = FeatureNormalizer()
        self.audio_normalizer.load_state_dict(norm_data['audio_normalizer'])

    @torch.no_grad()
    def predict_mfcc(self, emg: np.ndarray,
                     session_id: int = 0) -> np.ndarray:
        """
        EMG → predicted MFCCs.

        Args:
            emg: (n_samples, 8) raw EMG at 1000 Hz.
            session_id: Session index.

        Returns:
            mfcc: (n_frames, 26) predicted MFCC features.
        """
        # Preprocess
        filtered = preprocess_emg(emg, self.cfg.emg)
        features = extract_emg_features(filtered, self.cfg.emg)
        features = self.emg_normalizer.transform(features)

        # To tensor
        emg_t = torch.tensor(features, dtype=torch.float32).unsqueeze(0).to(self.device)
        sess_t = torch.tensor([session_id], dtype=torch.long).to(self.device)

        # Predict
        predicted = self.transducer.predict(emg_t, sess_t)
        return predicted.squeeze(0).cpu().numpy()

    @torch.no_grad()
    def synthesize(self, mfcc: np.ndarray) -> np.ndarray:
        """
        MFCCs → audio waveform via WaveNet.

        Args:
            mfcc: (n_frames, 26) MFCC features.

        Returns:
            audio: (n_samples,) waveform at 16 kHz.
        """
        mfcc_t = torch.tensor(mfcc, dtype=torch.float32).unsqueeze(0).to(self.device)

        # Number of audio samples = n_frames * hop_size
        n_samples = mfcc.shape[0] * 160

        # Generate
        quantized = self.wavenet.generate(mfcc_t, n_samples=n_samples)
        audio = mu_law_decode(quantized.cpu().numpy(), mu=255)
        return audio

    def __call__(self, emg: np.ndarray,
                 session_id: int = 0) -> np.ndarray:
        """Full pipeline: raw EMG → audio."""
        mfcc = self.predict_mfcc(emg, session_id)
        audio = self.synthesize(mfcc)
        return audio


# ─── Evaluation Metrics ───────────────────────────────────────────────────────

def compute_wer(reference: str, hypothesis: str) -> float:
    """
    Word Error Rate (Section 4):
        WER = (substitutions + insertions + deletions) / reference_length
    """
    ref_words = reference.lower().split()
    hyp_words = hypothesis.lower().split()

    # Levenshtein distance at word level
    n, m = len(ref_words), len(hyp_words)
    dp = [[0] * (m + 1) for _ in range(n + 1)]

    for i in range(n + 1):
        dp[i][0] = i
    for j in range(m + 1):
        dp[0][j] = j

    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if ref_words[i-1] == hyp_words[j-1]:
                dp[i][j] = dp[i-1][j-1]
            else:
                dp[i][j] = 1 + min(
                    dp[i-1][j],      # deletion
                    dp[i][j-1],      # insertion
                    dp[i-1][j-1],    # substitution
                )

    if n == 0:
        return float(m > 0)
    return dp[n][m] / n


def evaluate_batch(pipeline: SilentSpeechPipeline,
                   test_data: list, output_dir: str) -> dict:
    """
    Run inference on test set and compute metrics.

    Section 4.2.2: "automatic evaluation by transcribing system outputs
    with a large-vocabulary ASR system"
    """
    os.makedirs(output_dir, exist_ok=True)
    results = []

    for i, item in enumerate(test_data):
        # Generate audio
        audio = pipeline(item['silent_emg_raw'], session_id=item.get('session', 0))

        # Save audio
        output_path = os.path.join(output_dir, f'test_{i:04d}.wav')
        sf.write(output_path, audio, 16000)

        results.append({
            'id': i,
            'text': item.get('text', ''),
            'audio_path': output_path,
        })
        if (i + 1) % 10 == 0:
            print(f"  Generated {i+1}/{len(test_data)}")

    # NOTE: For automatic WER, pipe outputs through an ASR model
    # (e.g., Mozilla DeepSpeech as in the paper, or Whisper).
    # The WER computation requires a separate ASR step.
    print(f"\nGenerated {len(results)} audio files in {output_dir}/")
    print("To compute WER, transcribe these with an ASR system and compare "
          "against reference texts.")
    return results


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main(args):
    device = f'cuda:{args.gpu}' if torch.cuda.is_available() else 'cpu'

    pipeline = SilentSpeechPipeline(
        transducer_ckpt=args.transducer_ckpt,
        wavenet_ckpt=args.wavenet_ckpt,
        normalizer_path=args.normalizer_path,
        device=device,
    )

    # Single file inference
    if args.emg_path:
        emg = np.load(args.emg_path)
        audio = pipeline(emg, session_id=args.session_id)

        os.makedirs(args.output_dir, exist_ok=True)
        out_path = os.path.join(args.output_dir, 'output.wav')
        sf.write(out_path, audio, 16000)
        print(f"Audio saved to {out_path}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Silent Speech Inference')
    parser.add_argument('--emg_path', type=str, help='Path to raw EMG .npy file')
    parser.add_argument('--transducer_ckpt', type=str,
                        default='./checkpoints/best_transducer.pt')
    parser.add_argument('--wavenet_ckpt', type=str,
                        default='./checkpoints/wavenet/best_wavenet.pt')
    parser.add_argument('--normalizer_path', type=str,
                        default='./data/processed/processed_data.pkl')
    parser.add_argument('--output_dir', type=str, default='./outputs')
    parser.add_argument('--session_id', type=int, default=0)
    parser.add_argument('--gpu', type=int, default=0)
    args = parser.parse_args()
    main(args)
